f = "Fruit"
b = "Bread"
c = "Cake"
ch = "Cheese"
w = "Water"

CATEGORIES_TF = {'Avocado' : "Avocado",
 'Banana' : f,
 'Ciabatta, light, plain, parbaking' : b,
 'Fancy strudel with poppy stuff, own production' : c,
 'Flavored baguette loaf baked in the hearth, own production' : b,
 'Flavored wheat bread baked in the hearth, own production' : b,
 'Grain bread roll baked in the hearth, own production' : b,
 'Grapefruit' : f,
 'Kiwi' : f,
 'Lemon' : f ,
 'Lime' : f,
 'Mandarin' : f,
 'Mango' : f ,
 'Milk cakes' : ch ,
 'Milk desserts' : ch ,
 'Orange' : f ,
 'Plain baguette loaf baked in the hearth, own production' : b,
 'Plain baguette loaf, own production' : b ,
 'Plain bread roll baked in the hearth, own production' : b ,
 'Plain croissant, parbaking': b,
 'Plain fancy cake, own production' : c ,
 'Plain long loaf, own production' : b,
 'Plain rye-wheat bread, parbaking' : b,
 'Plain wheat bread, toast-type, own production' : b,
 'Pomegranate': f,
 'Rye-wheat grain bread baked in the hearth, own production' : b, 
 'Semi-hard bulk cheese' : ch,
 'Semi-hard coarse-pored cheese' : ch,
 'Semi-hard layered cheese' : ch ,
 'Small fancy bread with berry stuff, own production' : b,
 'Small flavored bread roll, own production' : b,
 'Soft cheese, white mold' : ch,
 'Sweet bun, own production' : b,
 'Water, import, sparkling' : w,
 'Water, slightly sparkling' : w,
 'Water, sparkling' : w ,
 'Water, still' : w,
 'Wheat bran bread baked in the hearth, own production' : b,
 'Yoghurts' : ch,
 }